### ISSUE TITLE
Unable to attach or mount volumes for assets pod

### ISSUE THREAD

**Issue by rept** [getkuby/kuby-digitalocean#1]
While following the QuickStart tutorial, I'm stuck at step 4:

    RAILS_MASTER_KEY=<your master key> bundle exec kuby -e production deploy

I'm getting this message:

    Unable to attach or mount volumes: unmounted volumes=[cavadou-assets-sa-token-rz2hw nginx-config assets], unattached volumes=[cavadou-assets-sa-token-rz2hw nginx-config assets]: error processing PVC cavadou-production/cavadou-assets: failed to fetch PVC from API server: persistentvolumeclaims "cavadou-assets" is forbidden: User "system:node:pool-0lnwggrn2-3pl92" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "cavadou-production": no relationship found between node "pool-0lnwggrn2-3pl92" and this object
Readiness probe failed: HTTP probe failed with statuscode: 404

**Comment by camertron** [comment]
@rept huh that's an error message I've never seen before. It seems to be saying the PVC (i.e. block storage) isn't reachable from the node your app is running on. If I had to guess, I'd say this sounds like a DigitalOcean bug. Have you tried deploying a second time or creating a new cluster? You could also reach out to their support.

Between you and me, I've found DigitalOcean's managed kubernetes offering to be a little flaky. I know, it's in all the Kuby examples, video, etc :( I recently moved to Linode and have been much happier.

**Comment by rept** [comment]
Switched to Linode and works there.
